---
- name: Set Homebrew prefix
  ansible.builtin.set_fact:
    homebrew_prefix: "{{ '/opt/homebrew' if ansible_architecture == 'arm64' else '/usr/local' }}"

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: brew_bin

- name: Install Homebrew
  ansible.builtin.shell: |
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_bin.stat.exists
  changed_when: true

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_casks }}"
