---
- name: Install python3
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    - python3-wheel
