---
- name: Include kubectl install tasks
  ansible.builtin.include_tasks: kubectl.yml

- name: Include talosctl install tasks
  ansible.builtin.include_tasks: talosctl.yml

- name: Include krew install tasks
  ansible.builtin.include_tasks: krew.yml

- name: Include helm install tasks
  ansible.builtin.include_tasks: helm.yml
