---
- name: Install cilium tools (macOS)
  community.general.homebrew:
    name:
      - cilium-cli
      - hubble
    state: present
  when: ansible_os_family == "Darwin"
  register: brew_cilium
  failed_when:
    - brew_cilium is failed
    - "'Error:' in (brew_cilium.msg | default(''))"

- name: Set cilium tools arch for Linux
  ansible.builtin.set_fact:
    cilium_arch: "{{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}"
  when: ansible_os_family == "Debian"

- name: Check if cilium is installed (Debian)
  ansible.builtin.stat:
    path: /usr/local/bin/cilium
  register: cilium_bin
  when: ansible_os_family == "Debian"

- name: Retrieve cilium-cli stable version
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
    return_content: true
  register: cilium_version
  changed_when: false
  when:
    - ansible_os_family == "Debian"
    - not cilium_bin.stat.exists

- name: Install cilium-cli (Debian)
  ansible.builtin.unarchive:
    src: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_version.content | trim }}/cilium-linux-{{ cilium_arch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"
  become: true
  when:
    - ansible_os_family == "Debian"
    - not cilium_bin.stat.exists

- name: Check if hubble is installed (Debian)
  ansible.builtin.stat:
    path: /usr/local/bin/hubble
  register: hubble_bin
  when: ansible_os_family == "Debian"

- name: Retrieve hubble stable version
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/cilium/hubble/main/stable.txt
    return_content: true
  register: hubble_version
  changed_when: false
  when:
    - ansible_os_family == "Debian"
    - not hubble_bin.stat.exists

- name: Install hubble (Debian)
  ansible.builtin.unarchive:
    src: "https://github.com/cilium/hubble/releases/download/{{ hubble_version.content | trim }}/hubble-linux-{{ cilium_arch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"
  become: true
  when:
    - ansible_os_family == "Debian"
    - not hubble_bin.stat.exists
